services:
  - type: web
    name: boyka-pairing-site
    env: docker
    plan: free
    branch: main
    repo: https://github.com/Joshuamambo1/boyka-pairing-site
    dockerfilePath: ./Dockerfile
    autoDeploy: true
